---
- 
  name: AMI Provisioning
  hosts: localhost
  become: true
  connection: local
  vars:
    URL_INSPECTOR: https://inspector-agent.amazonaws.com/linux/latest/install

  tasks:
    - name: Update all current packages
      yum:
        name: '*'
        state: latest

    - name: Install prerequisite packages
      yum:
        name: "{{ PACKAGES }}"
      vars:
        PACKAGES:
          - git
          - amazon-cloudwatch-agent
          - amazon-ssm-agent

    - name: Start Cloudwatch service
      systemd:
        name: amazon-cloudwatch-agent
        state: started
        enabled: true

    - name: Start Cloudwatch agent
      shell:
        cmd: |
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a start
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a status

    - name: Start SSM service
      systemd:
        name: amazon-ssm-agent
        state: started
        enabled: true

    - name: Install Docker
      yum:
        name: docker
        state: latest

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enable: true